"""initial schema

Revision ID: 139ee0ca88d8
Revises: 
Create Date: 2026-08-02 13:04:28.499281
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '139ee0ca88d8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cache_key', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feed_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feed_cache_cache_key'), ['cache_key'], unique=True)

    op.create_table('pools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('join_code', sa.String(length=40), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('num_games_per_week', sa.Integer(), nullable=False),
    sa.Column('target_nfl', sa.Integer(), nullable=False),
    sa.Column('target_ncaaf', sa.Integer(), nullable=False),
    sa.Column('sports', sa.JSON(), nullable=False),
    sa.Column('auto_publish', sa.Boolean(), nullable=False),
    sa.Column('open_registration', sa.Boolean(), nullable=False),
    sa.Column('current_week', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pools', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pools_join_code'), ['join_code'], unique=True)

    op.create_table('provider_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('calls', sa.Integer(), nullable=False),
    sa.Column('credits_used', sa.Integer(), nullable=False),
    sa.Column('remaining_reported', sa.Integer(), nullable=True),
    sa.Column('last_called_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'period', name='uq_provider_period')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('pool_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pool_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_in_pool', sa.String(length=16), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['pool_id'], ['pools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pool_id', 'user_id', name='uq_pool_member')
    )
    with op.batch_alter_table('pool_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pool_members_pool_id'), ['pool_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pool_members_user_id'), ['user_id'], unique=False)

    op.create_table('weeks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pool_id', sa.Integer(), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('lock_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lock_at_override', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('spread_refreshes', sa.Integer(), nullable=False),
    sa.Column('cfbd_calls', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['pool_id'], ['pools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pool_id', 'season_year', 'week_number', name='uq_pool_season_week')
    )
    with op.batch_alter_table('weeks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weeks_pool_id'), ['pool_id'], unique=False)

    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_id', sa.Integer(), nullable=False),
    sa.Column('league', sa.String(length=8), nullable=False),
    sa.Column('espn_event_id', sa.String(length=32), nullable=False),
    sa.Column('odds_api_id', sa.String(length=64), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('home_team', sa.String(length=120), nullable=False),
    sa.Column('away_team', sa.String(length=120), nullable=False),
    sa.Column('home_abbr', sa.String(length=12), nullable=False),
    sa.Column('away_abbr', sa.String(length=12), nullable=False),
    sa.Column('home_record', sa.String(length=20), nullable=True),
    sa.Column('away_record', sa.String(length=20), nullable=True),
    sa.Column('canonical_home_key', sa.String(length=120), nullable=False),
    sa.Column('canonical_away_key', sa.String(length=120), nullable=False),
    sa.Column('spread_home', sa.Float(), nullable=True),
    sa.Column('closeness', sa.Float(), nullable=True),
    sa.Column('spread_source', sa.String(length=16), nullable=True),
    sa.Column('in_slate', sa.Boolean(), nullable=False),
    sa.Column('slate_rank', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('winner', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['week_id'], ['weeks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week_id', 'espn_event_id', name='uq_week_event')
    )
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_games_canonical_away_key'), ['canonical_away_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_canonical_home_key'), ['canonical_home_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_espn_event_id'), ['espn_event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_week_id'), ['week_id'], unique=False)

    op.create_table('week_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pool_id', sa.Integer(), nullable=False),
    sa.Column('week_id', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('correct', sa.Integer(), nullable=False),
    sa.Column('possible', sa.Integer(), nullable=False),
    sa.Column('is_winner', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['pool_id'], ['pools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['week_id'], ['weeks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'week_id', name='uq_user_week')
    )
    with op.batch_alter_table('week_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_week_entries_pool_id'), ['pool_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_week_entries_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_week_entries_week_id'), ['week_id'], unique=False)

    op.create_table('picks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pool_id', sa.Integer(), nullable=False),
    sa.Column('week_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('picked_team', sa.String(length=8), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pool_id'], ['pools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['week_id'], ['weeks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'game_id', name='uq_user_game')
    )
    with op.batch_alter_table('picks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_picks_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_picks_pool_id'), ['pool_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_picks_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_picks_week_id'), ['week_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('picks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_picks_week_id'))
        batch_op.drop_index(batch_op.f('ix_picks_user_id'))
        batch_op.drop_index(batch_op.f('ix_picks_pool_id'))
        batch_op.drop_index(batch_op.f('ix_picks_game_id'))

    op.drop_table('picks')
    with op.batch_alter_table('week_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_week_entries_week_id'))
        batch_op.drop_index(batch_op.f('ix_week_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_week_entries_pool_id'))

    op.drop_table('week_entries')
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_games_week_id'))
        batch_op.drop_index(batch_op.f('ix_games_espn_event_id'))
        batch_op.drop_index(batch_op.f('ix_games_canonical_home_key'))
        batch_op.drop_index(batch_op.f('ix_games_canonical_away_key'))

    op.drop_table('games')
    with op.batch_alter_table('weeks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weeks_pool_id'))

    op.drop_table('weeks')
    with op.batch_alter_table('pool_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pool_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_pool_members_pool_id'))

    op.drop_table('pool_members')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('provider_usage')
    with op.batch_alter_table('pools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pools_join_code'))

    op.drop_table('pools')
    with op.batch_alter_table('feed_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feed_cache_cache_key'))

    op.drop_table('feed_cache')
    # ### end Alembic commands ###
