"""add commissioner invite code to pools

Revision ID: 176d4f464857
Revises: f6364f0b6497
Create Date: 2026-08-10 13:42:46.525663
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.auth import generate_join_code

revision: str = '176d4f464857'
down_revision: Union[str, None] = 'f6364f0b6497'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic, adjusted by hand ###
    # A second, independently rotatable code that gates creating a COMMISSIONER account for a
    # pool (POST /register?commissioner_code=...), deliberately never sharing storage or
    # rotation with Pool.join_code: the join code lets someone in as a plain member, this one
    # lets someone in as a commissioner, a materially more powerful action, and the product
    # owner was explicit that rotating one must never touch the other. See DECISIONS.md,
    # Post-launch fixes.
    with op.batch_alter_table('pools', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('commissioner_invite_code', sa.String(length=40), nullable=True)
        )
        batch_op.create_index(
            batch_op.f('ix_pools_commissioner_invite_code'),
            ['commissioner_invite_code'],
            unique=True,
        )

    # Nullable with no server default (unlike a shared value such as f6364f0b6497's scenario
    # columns), because every pool needs a DISTINCT code, not one copied value. Backfilled by
    # hand below instead: reuses app.auth.generate_join_code exactly, the same helper
    # POST /admin/leagues/new and POST /admin/join-code already use for the player join code,
    # so this never introduces a second code generator, and checks uniqueness against every
    # code already handed out in this same pass, the same collision-avoidance shape
    # rotate_join_code already uses. After this migration no pool is left with a null
    # commissioner_invite_code; new pools created going forward get their own fresh code at
    # creation time in POST /admin/leagues/new.
    bind = op.get_bind()
    pool_ids = [row[0] for row in bind.execute(sa.text('SELECT id FROM pools')).fetchall()]
    used: set[str] = set()
    for pool_id in pool_ids:
        code = generate_join_code()
        while code in used:
            code = generate_join_code()
        used.add(code)
        bind.execute(
            sa.text(
                'UPDATE pools SET commissioner_invite_code = :code WHERE id = :pool_id'
            ),
            {'code': code, 'pool_id': pool_id},
        )

    # autogenerate also proposed dropping and recreating ix_pool_members_paid_marked_by_user_id
    # on pool_members, the same false positive f6364f0b6497 already documented (SQLite's batch
    # table recreation reflecting an unrelated table's index back with a different apparent
    # identity); pool_members is untouched by this migration, so that step was removed by hand.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pools_commissioner_invite_code'))
        batch_op.drop_column('commissioner_invite_code')

    # ### end Alembic commands ###
