"""add is_test_week to weeks

Revision ID: 4efccffeb9cc
Revises: da27c5ef4f4f
Create Date: 2026-08-14 00:00:00.000000
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4efccffeb9cc'
down_revision: Union[str, None] = 'da27c5ef4f4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic, adjusted by hand ###
    # NOT NULL, so an existing week needs a server default to back-fill against, matching the
    # model's own Python side default (False): every week that already exists predates this
    # feature and is a real week, never a test week.
    with op.batch_alter_table('weeks', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'is_test_week', sa.Boolean(), nullable=False, server_default=sa.false()
            )
        )

    # New rows always go through the ORM, which sends an explicit value, so drop the server
    # default afterward to keep the schema matching app/models.py exactly.
    with op.batch_alter_table('weeks', schema=None) as batch_op:
        batch_op.alter_column('is_test_week', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weeks', schema=None) as batch_op:
        batch_op.drop_column('is_test_week')
    # ### end Alembic commands ###
