"""add scoring_mode and did_not_submit

Revision ID: 6aa4a2f020c6
Revises: d3ed4af188d3
Create Date: 2026-08-08 15:05:00.000000
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6aa4a2f020c6'
down_revision: Union[str, None] = 'd3ed4af188d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic, adjusted by hand ###
    # Both columns are NOT NULL, so existing rows need a server default to back-fill
    # against, matching the model's Python side defaults ("inverse" and False).
    with op.batch_alter_table('pools', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'scoring_mode', sa.String(length=16), nullable=False,
                server_default=sa.text("'inverse'"),
            )
        )

    with op.batch_alter_table('week_entries', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'did_not_submit', sa.Boolean(), nullable=False, server_default=sa.false()
            )
        )

    # The server defaults above exist only to back-fill existing rows. New rows go through
    # the ORM, which always sends an explicit value, so drop the defaults to keep the
    # schema matching app/models.py exactly.
    with op.batch_alter_table('pools', schema=None) as batch_op:
        batch_op.alter_column('scoring_mode', server_default=None)
    with op.batch_alter_table('week_entries', schema=None) as batch_op:
        batch_op.alter_column('did_not_submit', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('week_entries', schema=None) as batch_op:
        batch_op.drop_column('did_not_submit')

    with op.batch_alter_table('pools', schema=None) as batch_op:
        batch_op.drop_column('scoring_mode')
    # ### end Alembic commands ###
