"""add pinned games and rivalries

Revision ID: 6b6eab096a56
Revises: be7a7724eee3
Create Date: 2026-08-08 15:36:21.803545
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6b6eab096a56'
down_revision: Union[str, None] = 'be7a7724eee3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# The curated rivalry pairs (spec Section 6a / DECISIONS.md Phase 5), as canonical keys.
# Copied from app.models.DEFAULT_RIVALRIES's own canonical_key(...) output rather than
# imported live, so this migration keeps reading the same way years from now even if the
# team alias tables in app/providers/teams.py change later. Used only to back-fill any
# pool row that existed before this column did; every new pool from here on gets the same
# list from Pool.rivalries's own Python-side default.
_DEFAULT_RIVALRIES_JSON = (
    '[["ncaaf:ohio-state", "ncaaf:michigan"], ["ncaaf:auburn", "ncaaf:alabama"], '
    '["ncaaf:army", "ncaaf:navy"], ["ncaaf:michigan", "ncaaf:michigan-state"], '
    '["ncaaf:florida", "ncaaf:georgia"], ["ncaaf:texas", "ncaaf:oklahoma"], '
    '["ncaaf:usc", "ncaaf:notre-dame"]]'
)


def upgrade() -> None:
    # ### commands auto generated by Alembic, adjusted by hand ###
    # Both columns are NOT NULL, so an existing row needs a server default to back-fill
    # against. pinned backfills to false, a game nobody has pinned yet. rivalries backfills
    # to the same curated list a freshly seeded pool gets, matching this codebase's
    # "there is no real production pool yet" note (Phase 5 brief): existing local/demo pool
    # rows get the real curated list too, not an empty one.
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('pinned', sa.Boolean(), nullable=False, server_default=sa.false())
        )

    with op.batch_alter_table('pools', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'rivalries',
                sa.JSON(),
                nullable=False,
                server_default=sa.text(f"'{_DEFAULT_RIVALRIES_JSON}'"),
            )
        )

    # The server defaults above exist only to back-fill existing rows. New rows go through
    # the ORM, which always sends an explicit value (Game.pinned's Python default False,
    # Pool.rivalries's Python default DEFAULT_RIVALRIES), so drop the defaults to keep the
    # schema matching app/models.py exactly.
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.alter_column('pinned', server_default=None)
    with op.batch_alter_table('pools', schema=None) as batch_op:
        batch_op.alter_column('rivalries', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pools', schema=None) as batch_op:
        batch_op.drop_column('rivalries')

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('pinned')

    # ### end Alembic commands ###
