"""add picks_required to pools

Revision ID: 7f659398d6cc
Revises: 6aa4a2f020c6
Create Date: 2026-08-08 14:46:52.325980
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7f659398d6cc'
down_revision: Union[str, None] = '6aa4a2f020c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic, adjusted by hand ###
    # NOT NULL, so an existing pool needs a server default to back-fill against, matching
    # the model's Python side default (15).
    with op.batch_alter_table('pools', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'picks_required', sa.Integer(), nullable=False, server_default=sa.text('15')
            )
        )

    # The server default above exists only to back-fill existing rows. New rows go through
    # the ORM, which always sends an explicit value, so drop the default to keep the schema
    # matching app/models.py exactly.
    with op.batch_alter_table('pools', schema=None) as batch_op:
        batch_op.alter_column('picks_required', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pools', schema=None) as batch_op:
        batch_op.drop_column('picks_required')

    # ### end Alembic commands ###
