"""add venmo entry gate and payout rules

Revision ID: 8605b49060e6
Revises: 6b6eab096a56
Create Date: 2026-08-08 16:29:01.573285
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8605b49060e6'
down_revision: Union[str, None] = '6b6eab096a56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic, adjusted by hand ###
    # entry_fee, venmo_handle and payment_note are all nullable with no backfill: an existing
    # pool row has no real number or handle to backfill with, and inventing one would violate
    # the house rule that no dollar amount or Venmo handle is ever hard coded anywhere in this
    # build. payment_required_to_pick is NOT NULL, so it needs a server default to backfill an
    # existing row; true matches app/models.py's own Python-side default (Pool.payment_required_to_pick),
    # so an existing pool starts out requiring payment too, exactly like a brand new one, until
    # its commissioner configures Venmo details or switches it off.
    with op.batch_alter_table('pools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entry_fee', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('venmo_handle', sa.String(length=80), nullable=True))
        batch_op.add_column(
            sa.Column(
                'payment_required_to_pick',
                sa.Boolean(),
                nullable=False,
                server_default=sa.true(),
            )
        )
        batch_op.add_column(sa.Column('payment_note', sa.Text(), nullable=True))

    # All three PoolMember columns are nullable with no backfill: an existing member simply
    # has never been marked paid, has nobody recorded as having marked them, and has no Venmo
    # handle on file yet.
    with op.batch_alter_table('pool_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('paid_marked_by_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('member_venmo_handle', sa.String(length=80), nullable=True))
        batch_op.create_foreign_key(
            'fk_pool_members_paid_marked_by_user_id_users',
            'users',
            ['paid_marked_by_user_id'],
            ['id'],
            ondelete='SET NULL',
        )
        batch_op.create_index(
            batch_op.f('ix_pool_members_paid_marked_by_user_id'),
            ['paid_marked_by_user_id'],
            unique=False,
        )

    op.create_table(
        'payout_rules',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('pool_id', sa.Integer(), nullable=False),
        sa.Column('scope', sa.String(length=16), nullable=False),
        sa.Column('place', sa.Integer(), nullable=False),
        sa.Column('amount', sa.Float(), nullable=False),
        sa.Column('label', sa.String(length=120), nullable=True),
        sa.ForeignKeyConstraint(['pool_id'], ['pools.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('payout_rules', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_payout_rules_pool_id'), ['pool_id'], unique=False
        )

    # The server default on payment_required_to_pick exists only to back-fill existing rows.
    # New rows go through the ORM, which always sends an explicit value (the Python-side
    # default True), so drop it to keep the schema matching app/models.py exactly, following
    # the same pattern every earlier NOT NULL column addition in this codebase used.
    with op.batch_alter_table('pools', schema=None) as batch_op:
        batch_op.alter_column('payment_required_to_pick', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payout_rules')

    with op.batch_alter_table('pool_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pool_members_paid_marked_by_user_id'))
        batch_op.drop_constraint(
            'fk_pool_members_paid_marked_by_user_id_users', type_='foreignkey'
        )
        batch_op.drop_column('member_venmo_handle')
        batch_op.drop_column('paid_marked_by_user_id')
        batch_op.drop_column('paid_at')

    with op.batch_alter_table('pools', schema=None) as batch_op:
        batch_op.drop_column('payment_note')
        batch_op.drop_column('payment_required_to_pick')
        batch_op.drop_column('venmo_handle')
        batch_op.drop_column('entry_fee')
    # ### end Alembic commands ###
