"""add is_preview to pools

Revision ID: a3f7c9d21b46
Revises: 947d228f154d
Create Date: 2026-08-10 14:52:13.282521
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a3f7c9d21b46'
down_revision: Union[str, None] = '947d228f154d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic, adjusted by hand ###
    # NOT NULL, so an existing pool needs a server default to back-fill against. Unlike most
    # other columns in this codebase, the server default is kept rather than dropped
    # afterward (Post-launch fixes, see DECISIONS.md): app/models.py's own mapped_column
    # declares server_default="false" too, on purpose, so the column stays self-evidently
    # false for any row inserted outside the ORM as well.
    with op.batch_alter_table('pools', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'is_preview', sa.Boolean(), nullable=False, server_default=sa.false()
            )
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pools', schema=None) as batch_op:
        batch_op.drop_column('is_preview')

    # ### end Alembic commands ###
