"""add locked_at to week_entries

Revision ID: be7a7724eee3
Revises: 7f659398d6cc
Create Date: 2026-08-08 15:14:52.764336
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'be7a7724eee3'
down_revision: Union[str, None] = '7f659398d6cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic, adjusted by hand ###
    # Nullable, no backfill needed: an existing week_entries row simply has never been
    # player-locked (matches app/models.py's WeekEntry.locked_at exactly).
    with op.batch_alter_table('week_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('week_entries', schema=None) as batch_op:
        batch_op.drop_column('locked_at')
    # ### end Alembic commands ###
