"""add per-league week resolution columns

Revision ID: d3ed4af188d3
Revises: 139ee0ca88d8
Create Date: 2026-08-08 13:50:54.328754
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd3ed4af188d3'
down_revision: Union[str, None] = '139ee0ca88d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic, adjusted by hand ###
    # week1_anchor_date and anchor_date are nullable: an existing pool or week that predates
    # this feature simply has none, and the fallback in app/services/ingest.py handles that.
    # resolved_weeks and is_bowl_week are NOT NULL, so existing rows need a server default to
    # back-fill against, matching the model's Python side defaults ({} and False).
    with op.batch_alter_table('pools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('week1_anchor_date', sa.Date(), nullable=True))

    with op.batch_alter_table('weeks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('anchor_date', sa.Date(), nullable=True))
        batch_op.add_column(
            sa.Column(
                'resolved_weeks', sa.JSON(), nullable=False, server_default=sa.text("'{}'")
            )
        )
        batch_op.add_column(
            sa.Column(
                'is_bowl_week', sa.Boolean(), nullable=False, server_default=sa.false()
            )
        )

    # The server defaults above exist only to back-fill existing rows. New rows go through
    # the ORM, which always sends an explicit value, so drop the defaults to keep the schema
    # matching app/models.py exactly.
    with op.batch_alter_table('weeks', schema=None) as batch_op:
        batch_op.alter_column('resolved_weeks', server_default=None)
        batch_op.alter_column('is_bowl_week', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weeks', schema=None) as batch_op:
        batch_op.drop_column('is_bowl_week')
        batch_op.drop_column('resolved_weeks')
        batch_op.drop_column('anchor_date')

    with op.batch_alter_table('pools', schema=None) as batch_op:
        batch_op.drop_column('week1_anchor_date')

    # ### end Alembic commands ###
