"""add scenario engine columns

Revision ID: f6364f0b6497
Revises: 8605b49060e6
Create Date: 2026-08-08 17:26:42.156365
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f6364f0b6497'
down_revision: Union[str, None] = '8605b49060e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic, adjusted by hand ###
    # Both moneyline columns are nullable with no backfill: an existing Game row has no real
    # American odds to invent, and app.scenarios.win_probability already falls back to the
    # spread derived model whenever a moneyline is null, so leaving every existing row null
    # is the correct, honest starting state, not a gap to paper over.
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_moneyline', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('away_moneyline', sa.Integer(), nullable=True))

    # Both are NOT NULL, so a server default backfills an existing pool row to the same
    # numbers app/models.py's own Python-side defaults use (5 final games, 1 remaining),
    # following the same pattern every earlier NOT NULL column addition in this codebase
    # used (see 8605b49060e6, payment_required_to_pick).
    with op.batch_alter_table('pools', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'scenarios_min_final_games', sa.Integer(), nullable=False, server_default='5'
            )
        )
        batch_op.add_column(
            sa.Column(
                'scenarios_min_remaining_games', sa.Integer(), nullable=False, server_default='1'
            )
        )

    # The server defaults above exist only to back-fill existing rows. New rows go through
    # the ORM, which always sends an explicit value, so drop them to keep the schema
    # matching app/models.py exactly, the same cleanup 8605b49060e6 already did.
    with op.batch_alter_table('pools', schema=None) as batch_op:
        batch_op.alter_column('scenarios_min_final_games', server_default=None)
        batch_op.alter_column('scenarios_min_remaining_games', server_default=None)

    # autogenerate also proposed dropping and recreating ix_pool_members_paid_marked_by_user_id
    # on pool_members, a false positive from SQLite's batch table recreation reflecting the
    # index back with a different apparent identity; pool_members is untouched by this
    # migration, so that step was removed by hand.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pools', schema=None) as batch_op:
        batch_op.drop_column('scenarios_min_remaining_games')
        batch_op.drop_column('scenarios_min_final_games')

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('away_moneyline')
        batch_op.drop_column('home_moneyline')

    # ### end Alembic commands ###
